services:
  ollama:
    image: "ollama/ollama"
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    ports:
      - "11434:11434"
    volumes:
      - ./.dockerTemps/ML:/root/.ollama/models
  redis:
    image: "redislabs/redisearch:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./.dockerTemps/DB:/data/
  ragdemo:
    build:
      context: .
      dockerfile: RAGDemo/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis
      - ollama
